### ISSUE TITLE
🔧 [기능요청][답변] AnswerPost 반환시 채택답변 존재시 , 채택된 답변이 1번으로 오게 수정 필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#411]
🗒️ 설명
---
현재는 Post에 대한 답변리스트 반환시

Sort 조건은 CreateDate으로 합니다

반환되는 Page 객체의 content 에서 채택된 답변 조회후 
채택순서는 최상위로 바꿔서 다시 반환하는 로직 필요

더 좋은 방법이 있으면 검색해봐야될것같긴합니다 

🙋‍♂️ 담당자
---
- 백엔드: 백지훈
- 프론트엔드: 이유진

**Comment by Chuseok22** [comment]
@newjinlee 
/api/answer/get/all 요청 시 채택 된 답변이 있다면 최상단에, 다른 글들은 최신순으로 정렬하여 반환되게 수정했습니다.

**Comment by newjinlee** [comment]
확인했습니다 ~
