### ISSUE TITLE
🔧 [기능요청][인증] api/auth/refresh API에 userName 추가 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#412]
🔍 설명
---
랜딩페이지에서 userName 보여주기 위해 
/api/auth/refresh API의 response값에
{
  "accessToken": "string",
  "isValidToken": true
}

userName추가 부탁드립니다

🙋‍♂️ 담당자
---
- 백엔드: 서새찬
- 프론트엔드: 손재호

**Comment by Cassiiopeia** [comment]
#414 

추가하였습니다

기본적인 로직과 동일성을위해 

기존 Member안에 있었던 확생이름변수인 studentName 으로 반환합니다

<img width="250" alt="image" src="https://github.com/user-attachments/assets/13e8ed8d-4fae-4d13-b684-5f255fa49aaf">

userName 이 아닌
studentName 에 추가되어 반환됩니다. 확인부탁드립니다

**Comment by thswogh** [comment]
확인했습니다 수고하셨습니다
