### ISSUE TITLE
❗ [버그][로그아웃] 로그아웃 api 호출 시 refreshToken가 삭제되지 않는 버그 수정 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#424]
🗒️ 설명
/api/auth/logout 요청 시, 서버측에서 헤더에 존재하는 refreshToken을 삭제하지 않는 버그가 있습니다.
Set-Cookie 헤더로 쿠키값을 설정하고 HttpOnly옵션이 설정 되어 있어, logout요청 시 서버측에서 refreshToken을 삭제해주어야 합니다

🙋‍♂️ 담당자
- 백엔드: 서새찬
- 프론트엔드: 손재호

**Comment by Cassiiopeia** [comment]
@thswogh 

프론트엔드에서 로그아웃 요청 시 credentials 포함 여부 확인하라고 하는데 잘 설정되어있는건가요?

```
import axios from 'axios';

const logout = async () => {
  try {
    await axios.post('/api/auth/logout', {}, { withCredentials: true });
    // 로그아웃 성공 처리
  } catch (error) {
    console.error('로그아웃 실패:', error);
    // 에러 처리
  }
};

```

**Comment by thswogh** [comment]
ogout API 호출 시,refreshToken이 정상적으로 삭제됩니다
