### ISSUE TITLE
⚙️ [기능추가][검색] 검색 페이지 Init

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-BE#438]
🗒️ 설명
---
- 사용자가 입력한 검색어와 과목명에 따라 여러 유형의 게시글을 검색하고 결과를 반환하는 서비스 입니다.
- `QuestionPost`, `DocumentPost`, `DocumentRequestPost`, `NoticePost`에 작성된 글에 대해 검색 기능을 제공합니다.
- 파라미터 : `String query`, `String subject`, `Integer pageNumber`, `Integer pageSize`
- 질문, 자료, 자료 요청, 공지사항 게시글 중 제목과 분문에 해당 검색어를 포함하는 글을 반환합니다.
- 2024.11.26. 공지사항 게시판은 null로 반환됩니다. (추후 수정)

🙋‍♂️ 담당자
---
- 백엔드: 백지훈
- 프론트엔드: 손재호
- 디자인:

**Comment by thswogh** [comment]
확인했습니다~

**Comment by Cassiiopeia** [comment]
이슈 닫습니다~
