### ISSUE TITLE
❗ [버그][답변] AnswerPostLike 에 관한 Entity 부재

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#443]
🗒️ 설명
---
- 답변에 대한 좋아요 로직이 존재하지않습니다 Mongo Entity를 추가해야합니다

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22

**Comment by Chuseok22** [comment]
이부분 제가 만들까요?

**Comment by Cassiiopeia** [comment]
넵넵 좋습니다. 추가적으로 CommetLike 관련 로직도 없습니다. 아직 FE 이슈생성하지는 않았습니다만 어느정도 수정이 된것으로 알고있습니다

담당자 백지훈으로 변경합니다
