### ISSUE TITLE
🔧 [기능요청][인기자료] 인기자료 인지 확인하는 로직필요

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#478]
🗒️ 설명
---
- 마이페이지를 보면 올린 인기자료 부분을 계산한다
- 나의자료가 얼마나 인기자료에 올라갔는지 체크할수있다
- 그래서 DocumentPost 에 isPopular 라는 칼럼을 추가했다.

이에 대한 인기자료에 한번이라도 올라갔을시 isPopular를 true로 만들어야하는 로직이 필요하다

이부분에 대해서 인기자료를 측정할때 최소 좋아요 개수를 5개로 정합시다
( 더 좋은 방법있으면 추천해주세요~! )
인기자료 올라가는기준은 일간, 주간, 월간? 어디까지 구현되어있는지 봐야 알것같습니다만 이때 인기자료에 올라갔었는지 여부를 판단하면될것같습니다

인기자료 개수 에 대한 repo 메소드는 존재합니다
 long countByMemberAndIsPopularTrue(Member member);

![image](https://github.com/user-attachments/assets/a8f818eb-0afa-471d-b772-867aeec686a5)
![image](https://github.com/user-attachments/assets/d11528fe-abd6-4bee-a9d8-561124345baf)
<img width="356" alt="image" src="https://github.com/user-attachments/assets/79cc611a-9a8e-43a9-b32a-731215a554bd">
<img width="355" alt="image" src="https://github.com/user-attachments/assets/11fe8917-db4d-4960-aa2e-82ec2193b259">

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22

**Comment by Chuseok22** [comment]
확인했습니다~

**Comment by Chuseok22** [comment]
<질문게시판 인기글>
1. 일간 인기 질문 글
- 현재 시각으로부터 24시간 이내에 작성된 질문글을 대상으로 일간 인기 점수가 높은 순으로 정렬하여 반환합니다.
- 스케줄러를 사용하여 30분마다 인기 점수를 갱신합니다.

2. 주간 인기 질문 글
- 현재 시각으로부터 7일 이내에 작성된 질문글을 대상으로 주간 인기 점수가 높은 순으로 정렬하여 반환합니다.
- 스케줄러를 사용하여 6시간마다 인기 점수를 갱신합니다.

<자료게시판 인기글>
1. 일간 인기 자료 글
- 좋아요 개수가 10개 이상인 글에 대해서 일간 인기 점수를 계산하며 점수가 높은 순으로 정렬하여 반환합니다.
- 스케줄러를 사용하여 매일 자정마다 일간 인기 점수가 초기화됩니다.

2. 주간 인기 자료 글
- 좋아요 개수가 10개 이상인 글에 대해서 주간 인기 점수를 계산하며 점수가 높은 순으로 정렬하여 반환합니다.
- 스케줄러를 사용하여 월요일 자저암다 주간 인기 점수가 초기화됩니다.

<isPopular 설정>
일간/주간을 포함하여 인기 자료 글 상위 10개까지의 글의 isPopular의 값을 true로 설정합니다.
(인기글 목록에서는 프론트가 요청 한 개수만큼의 글을 반환해줍니다. 반환해준 글의 isPopular을 모두 true로 변경하게되면 인기글의 가치가 떨어질 것 같아 상위 10개까지의 글로 제한했습니다.)

**Comment by Chuseok22** [comment]
<질문게시판 인기글>

일간 인기 질문 글
현재 시각으로부터 24시간 이내에 작성된 질문글을 대상으로 일간 인기 점수가 높은 순으로 정렬하여 반환합니다.
스케줄러를 사용하여 30분마다 인기 점수를 갱신합니다.
주간 인기 질문 글
현재 시각으로부터 7일 이내에 작성된 질문글을 대상으로 주간 인기 점수가 높은 순으로 정렬하여 반환합니다.
스케줄러를 사용하여 6시간마다 인기 점수를 갱신합니다.
<자료게시판 인기글>

일간 인기 자료 글
좋아요 개수가 10개 이상인 글에 대해서 일간 인기 점수를 계산하며 점수가 높은 순으로 정렬하여 반환합니다.
스케줄러를 사용하여 매일 자정마다 일간 인기 점수가 초기화됩니다.
주간 인기 자료 글
좋아요 개수가 10개 이상인 글에 대해서 주간 인기 점수를 계산하며 점수가 높은 순으로 정렬하여 반환합니다.
스케줄러를 사용하여 월요일 자정마다 주간 인기 점수가 초기화됩니다.
<isPopular 설정>
일간/주간을 포함하여 인기 자료 글 상위 30개까지의 글의 isPopular 값을 true로 설정합니다.
질문/자료 인기글은 PopularPost 테이블에 저장되며 api 요청 시 해당 테이블에 있는 글들을 반환합니다.
@minhong620 @Cassiiopeia @thswogh @newjinlee
