### ISSUE TITLE
🔧 [기능요청][답변조회] mediaFiles response 값 추가 요청

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-BE#483]
🗒️ 설명
---
- 사진을 등록을 하면 보여줘야겠지?

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: @newjinlee

**Comment by Chuseok22** [comment]
ㅎㅎ... 구현했습니다
