### ISSUE TITLE
🔧 [기능요청][api요청] 자료게시판에서 필요한 api 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#488]
🗒️ 설명
자료게시판 메인페이지에서 필요한 api 요청합니다.
HOT 다운로드 부분 api가 필요합니다
![image](https://github.com/user-attachments/assets/0b5e748b-246b-4271-90f0-c78233d93b96)

🙋‍♂️ 담당자
- 백엔드: 백지훈
- 프론트엔드: 손재호

**Comment by Chuseok22** [comment]
확인했습니다 ㅎㅎ

**Comment by thswogh** [comment]
구현되면 태그해주세요~

**Comment by Chuseok22** [comment]
@thswogh 확인부탁드립니다~

**Comment by thswogh** [comment]
확인했습니다~!
