### ISSUE TITLE
🔧 [기능요청][api요청] /api/document/post 추가 파라미터 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#489]
🗒️ 설명

현재 스웨거 상의 /api/document/post의 요청 파라미터는 다음과 같이 6개입니다
- title (String, 필수)
- content (String, 필수)
- subject (String, 필수)
- documentTypeSet (String, 선택)
- isDepartmentPrivate (Boolean, 선택): 내 학과 비공개 여부 : 기본값 false (공개)
- attachmentFiles (MultipartFile, 선택): 업로드 자료 파일 리스트 

<hr/>

피그마의 자료글등록 페이지를 구현하려면 추가적인 파라미터가 필요합니다
<img width="302" alt="image" src="https://github.com/user-attachments/assets/072b0a16-11db-4f37-a8b8-692437f303c1">
1. documentTypeSet이 필수로 바뀌어야 합니다
2. `수강년도 선택`에 대한 파라미터가 추가되어야 합니다
3. `커스텀 태그`에 대한 파라미터가 추가되어야 합니다

🙋‍♂️ 담당자
- 백엔드: 백지훈, 서새찬
- 프론트엔드: 손재호

**Comment by Chuseok22** [comment]
확인했습니다 ㅎㅎ

**Comment by Cassiiopeia** [comment]
@Chuseok22 지훈님이 작업하시나요??

**Comment by Chuseok22** [comment]
@Cassiiopeia 구러면 새찬님께서 작업해주시는걸로 ㅎㅎ

**Comment by Cassiiopeia** [comment]
> @Cassiiopeia 구러면 새찬님께서 작업해주시는걸로 ㅎㅎ

네네~

**Comment by Cassiiopeia** [comment]
@thswogh  커스텀 태그 파라미터가 무슨뜻인가요?

**Comment by thswogh** [comment]
@Cassiiopeia  피그마에 보이는 것처럼 사용자가 자료등록 시, 지정하는 커스텀 태그입니다. 
프론트에서는 최대4개, 태그당 최대 10글자로 설정해놓았습니다

**Comment by Cassiiopeia** [comment]
> @Cassiiopeia 피그마에 보이는 것처럼 사용자가 자료등록 시, 지정하는 커스텀 태그입니다. 프론트에서는 최대4개, 태그당 최대 10글자로 설정해놓았습니다

확인했습니다 로직 추가할께요

**Comment by thswogh** [comment]
정상 작동 확인했습니다
