### ISSUE TITLE
❗ [버그][api 로직]  /api/document-request/filter API 버그

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#498]
🗒️ 설명
 /api/document-request/filter API를 요청하면
 terimus 상에서 다음과 같은 오류를 출력합니다.
- ERROR 1 --- [io-8080-exec-10] c.b.s.s.DocumentRequestPostService       : 자료요청게시판은 중인 이상 접근이 가능합니다. 21011761 의 엽전 수: 200
- ERROR 1 --- [io-8080-exec-10] c.b.s.u.e.GlobalExceptionHandler         : 사용자의 엽전이 부족합니다.

<hr/>

자료요청 게시판은 중인등급 이상이 아니라 천민등급의 사용자도 접근이 가능해야할 것 같습니다. 
하단의 사진처럼 자료게시판 메인페이지에서 `자료요청`이 보여야 하니 천민등급부터 가능해야할 것 같습니다

![image](https://github.com/user-attachments/assets/ef141995-78da-4aa2-8583-cdd3baabb89b)

🙋‍♂️ 담당자

- 백엔드: 백지훈
- 프론트엔드: 손재호

**Comment by Chuseok22** [comment]
확인했습니다~ 수정해놓을게요
