### ISSUE TITLE
🔧 [기능요청][마이페이지] 레벨 생성에 따른 마이페이지 반환값 추가 요청

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#509]
🗒️ 설명
---
- 경험치 레벨 도입에 따라 여러값들이 추가되어야합니다
- 각각 레벨은 경험치 500단위로 하기로하였습니다 
- 총 18개의 단계가있습니다 

백은 관리직에 대한정보를 알파벳순서대로 (가장높은 1품정은 A) 입니다
이렇게 보내주기로하였고 
progressbar 를 구현해야하기때문에 각각 알파벳마다 
첫 마지막 을 보내야합니다

예를들면 r 이 젤 마지막인데
r이면 경험치시작인 0 과 r계급경험치의 끝인 500을 보내줘야합니다
0과 500중 내 현재 경험치가 50이면
퍼센티지 10 도 같이보내야합니다

해당부분 추가해야합니다

![image](https://github.com/user-attachments/assets/b54f3ac2-4279-4d6b-9460-a4573ab55bc6)

https://www.kyobo.com/dgt/web/kbstory/contents/detail/1567

http://www.daebosa.co.kr/html/07/09.php

![image](https://github.com/user-attachments/assets/654c8d9f-865f-4600-bfb9-e8664a7e74ba)

조선시대의 
- 현재 디자인
![image](https://github.com/user-attachments/assets/1cfe9d9c-e741-454d-9306-f953248e4f01)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee

**Comment by Cassiiopeia** [comment]
myPage 반환값 개선 및 수정사항이 있습니다

https://github.com/Sejong-Balsamic/Malsami-FE/issues/236

확인 부탁드립니다

**Comment by newjinlee** [comment]
확인했습니다!
