### ISSUE TITLE
🔥🔧 [긴급][기능요청] user의 faculty만 얻어오는 api 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#513]
🗒️ 설명

현재 자료게시판 메인페이지에서 user의 faculty를 얻어오기 위해 /api/member/my-page API를 호출합니다.
faculty 변수가 필요한데 /api/member/my-page API를 호출하는 것은 비효율적입니다.
-> `내 전공`인 `faculty`변수만 반환값으로 넘겨주는 API 요청합니다.
<img width="637" alt="image" src="https://github.com/user-attachments/assets/08e2b618-3a24-4cc5-99ae-55336e1416d4">

🙋‍♂️ 담당자
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
확인했습니다~!

**Comment by Cassiiopeia** [comment]
변경내용
---
회원정보만 반환하는 API 추가하였습니다
인증이 필요한 API입니다
POST
/api/member/my-info
입니다

예시 반환값
```
{
  "member": {
    "createdDate": "2024-11-29T22:00:13.555521",
    "updatedDate": "2024-11-30T02:27:41.243297",
    "isEdited": true,
    "isDeleted": false,
    "isLiked": false,
    "memberId": "b94fded2-7b0b-49e6-928b-8f1685452f0c",
    "studentId": 18010561,
    "studentName": "서새찬",
    "uuidNickname": "d3496f",
    "major": "바이오융합공학전공",
    "academicYear": "4",
    "enrollmentStatus": "졸업",
    "profileUrl": null,
    "isNotificationEnabled": true,
    "roles": [
      "ROLE_USER",
      "ROLE_ADMIN"
    ],
    "accountStatus": "ACTIVE",
    "lastLoginTime": "2024-11-30T02:27:41.069232"
  },
  "major": null,
  "studentIdString": null,
  "studentName": null,
  "academicYear": null,
  "enrollmentStatus": null,
  "accessToken": null,
  "refreshToken": null,
  "yeopjeon": null,
  "exp": null,
  "isFirstLogin": null,
  "isAdmin": null,
  "yeopjeonRank": null,
  "totalYeopjeon": null,
  "yeopjeonPercentile": null,
  "expRank": null,
  "totalExp": null,
  "expPercentile": null,
  "totalLikeCount": null,
  "totalPopularPostCount": null,
  "totalCommentCount": null,
  "totalPostCount": null,
  "questionPostCount": null,
  "answerPostCount": null,
  "documentPostCount": null,
  "documentRequestPostCount": null
}
```
<img width="562" alt="image" src="https://github.com/user-attachments/assets/0ca0de57-6133-4235-b89f-1071d20927ac">
<img width="427" alt="image" src="https://github.com/user-attachments/assets/e9ad438b-1703-43f1-871b-4401e58e36c2">

**Comment by Chuseok22** [comment]
@Cassiiopeia faculty부분 추가해야할 것 같아여

**Comment by thswogh** [comment]
@Cassiiopeia `major` 외에 학부인 `faculty`도 추가로 반환되어야 합니다.

예시)
major: 소프트웨어학과
faculty: 소프트웨어융합대학

**Comment by Cassiiopeia** [comment]
@thswogh 아하 그렇군요 확인했습니다

**Comment by Cassiiopeia** [comment]
@thswogh  이부분도 동일합니다 member안에 단과대 정보가있어 my-info API에 faculty정보가 같이 넘어갑니다
확인부탁드립니다

**Comment by Cassiiopeia** [comment]
해당부분 확인되어 이슈 닫습니다
