### ISSUE TITLE
❗ [버그][자료요청] 랜딩페이지용 자료 요청 버그

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-BE#517]
🗒️ 설명
---
- 전체 자료를 조회하기 위한 api /api/landing/document 가 반환값을 제대로 뱉지 않습니다 ~ 확인부탁드립니다 ~
- ![image](https://github.com/user-attachments/assets/edac7905-4cbb-4135-8b0b-f8df095247cc)

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: @newjinlee

**Comment by Cassiiopeia** [comment]
확인했습니다 제가 일단 확인해보겠습니다. 담당자에 추가하였습니다

**Comment by Cassiiopeia** [comment]
@newjinlee  어떤 요청을 보냈는데 500에러가 떴는지 알려주세요

**Comment by Cassiiopeia** [comment]
토큰 없어도
해당 API 정상 documentPost 반환 확인하였습니다
@newjinlee 

![image](https://github.com/user-attachments/assets/22fe7211-a5d5-4b5f-8a25-568b5cbdc374)

**Comment by newjinlee** [comment]
확인했습니다!
