### ISSUE TITLE
🔥⚙️  [긴급][기능추가][api요청] 각 게시판 접근 권한 반환해주는 api 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#521]
🗒️ 설명
---
사용자의 엽전 개수에 따라 천민/중인/양반/왕 게시판 접근권한이 달라집니다.
기존의 코드는 프론트에서 사용자의 엽전 개수를 받고, 프론트에서 계산 해 각 게시판 접근권한을 계산하였습니다.
백엔드에서 사용자의 각 게시판 접근권한을 주는 것이 더 효율적이고 코드유지 보수가 용이할 것 같아, 새 api 요청합니다.

예상 api
- 엔드포인트: api/member/userPermissions
- 요청파라미터:`accessToken` (사용자 인식하기 위해)
- 반환파라미터: 
<table>
  <thead>
    <tr>
      <th>변수명</th>
      <th>타입</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>canAccessCheonmin</td>
      <td>boolean</td>
    </tr>
    <tr>
      <td>canAccessJungin</td>
      <td>boolean</td>
    </tr>
    <tr>
      <td>canAccessYangban</td>
      <td>boolean</td>
    </tr>
    <tr>
      <td>canAccessKing</td>
      <td>boolean</td>
    </tr>
  </tbody>
</table>

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
확인했습니다

**Comment by Cassiiopeia** [comment]
추가적으로 
엽전 기준값 반환합니다
확인 부탁드립니다

          - **`Integer cheonminRequirement`**: 천민 게시판 접근 요구 엽전
          - **`Integer junginRequirement`**: 중인 게시판 접근 요구 엽전
          - **`Integer yangbanRequirement`**: 양반 게시판 접근 요구 엽전
          - **`Integer kingRequirement`**: 왕 게시판 접근 요구 엽전

![image](https://github.com/user-attachments/assets/edce745e-f729-4258-9166-8204848f24b9)

**Comment by thswogh** [comment]
/api/member/document/access-info로 api 수정했습니다
