### ISSUE TITLE
❗ [버그][엽전] 엽전현상금이 없을 경우 REWARD_YEOPJEON 0인것이 yeopjeonHistory 에 쌓이는 문제

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#525]
🗒️ 설명
---
- 현재 구현 로직을 보면

엽전현상금이 없는 게시글을 생성하면
다음과 같이 REWARD_YEOPJEON 인 
yeopjeonHistory가 쌓입니다

엽전현상금이 0일때는 history를 생성하지않아야합니다
예외처리 부탁드립니다

<img width="567" alt="image" src="https://github.com/user-attachments/assets/1996aeb1-78fd-4d63-bdcc-62b4d8111678">

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22

**Comment by Chuseok22** [comment]
확인했습니다~
