### ISSUE TITLE
🔥⚙️ [긴급][기능추가][api수정] 검색 api 수정 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#530]
🗒️ 설명
---
현재 스웨거에서 `/api/query`는 다음과 같이 요청파라미터를 보내게 되어있습니다.
![image](https://github.com/user-attachments/assets/670b0d75-ef75-4bd7-b7d8-8ff13b04f276)

디자인 상으로는 질문게시판, 자료게시판마다 필터링 기능이 있습니다
질문게시판은 "엽전현상금", 자료게시판은 "각 티어 게시판"이 필터가 되어야 합니다

> 결론: 질문게시판, 자료게시판 필터링 기능을 구현해주세요!

1. api/query/document, api/query/question이런식으로 바꾸거나
2. 요청 파라미터에 필터 한번에 보내도 되고..! 
더 좋은 방법 있으면 코멘트 남겨주세요~
![image](https://github.com/user-attachments/assets/679240f5-79f8-4489-9af1-01e0de89b976)

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
@thswogh 논의한 결과

해당사항은 2개의 api를 호출하는쪽으로 보면됩니까?

변경사항은 따로 필요없는거죠?

교과목명은 현재까지는 아무것도 안보내는것이겠네요??
( 추후에 @교과목명 으로 개선하는 방향으로 이해했습니다 )

**Comment by Chuseok22** [comment]
요거는 카톡에서 해결된 내용이므로 이슈 닫겠습니다~
