### ISSUE TITLE
🔥❗🔥❗[긴급][버그][api] /api/member/my-page 403 오류

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-BE#532]
🗒️ 설명
---
- 신규 로그인 시 /api/member/my-page 호출 시 403 오류가 뜹니다.
- 기존 회원 로그인했을 때는 문제 없습니다. 
![image](https://github.com/user-attachments/assets/782d73ca-b131-4d94-8e14-4904172c0a09)
![image](https://github.com/user-attachments/assets/07334e44-9b73-4809-a585-7195d9821a37)
![image](https://github.com/user-attachments/assets/52d28be4-a233-4e23-bd20-0edd3d42f131)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee

**Comment by Cassiiopeia** [comment]
https://github.com/Sejong-Balsamic/Malsami-BE/commit/e3b8beef5dad7b48171b38175e0b0191c29356c7

죄송합니다 ^^

AI 검수를 못했습니다

**Comment by Chuseok22** [comment]
@Cassiiopeia 아조씨 GPT 복붙...
