### ISSUE TITLE
🔥❗[긴급][버그] 로그인 signin API호출 시 에러

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#546]
🗒️ 설명
---
/api/member/signin 요청 시, 에러가 나옵니다
![image](https://github.com/user-attachments/assets/ba792411-45b6-4968-898d-76bbdc623b1e)
![image](https://github.com/user-attachments/assets/5de7d34e-b969-451d-b2fe-fee082dc8a4b)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
해당부분에 대해서

member 부분을 List<String> Faculty 로 반환시키는것으로 합의했습니다

@Chuseok22

**Comment by Cassiiopeia** [comment]
<img width="461" alt="image" src="https://github.com/user-attachments/assets/5e054011-00ce-447a-a677-bc5cdde1aa77">

<img width="419" alt="image" src="https://github.com/user-attachments/assets/d4a67bcb-7e5b-4de4-ab13-6045a1e2f4f3">

저는 해당하는 단과대가 하나라

표시가 잘안됩니다

테스트 부탁드립니다

/api/member/signin
/api/member/my-page

2 API 테스트 하였습니다

**Comment by thswogh** [comment]
/api/member/signin
/api/member/my-page
테스트 결과입니다

![image](https://github.com/user-attachments/assets/d587ebce-ca52-4209-972e-c88f5e1ba617)
![image](https://github.com/user-attachments/assets/bc09d2b0-d366-4882-b028-777c6828f8bc)

**Comment by Cassiiopeia** [comment]
확인되어 이슈 닫습니다
