### ISSUE TITLE
🔥 ❗[긴급][버그][질문메인] 전체 선택시 게시글 못불러오는 문제

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#551]
🗒️ 설명
---
- 제가 현재 faculty를 동적으로 받아서 member의 학과에 따라서 단과대가 여러개를 저장 시킬수있게 개선작업을 하였는데요
기존 faculty를 불러오는 방법이나 쿼리문이 잘 작동을 안하는것같습니다

![image](https://github.com/user-attachments/assets/d1c0d50f-034c-43b7-bf86-764ee994ff34)

![image](https://github.com/user-attachments/assets/6b82d473-4505-45d3-bb39-0c54cd21dcc9)

![image](https://github.com/user-attachments/assets/1fb4cd72-158d-43c2-848c-5e66ab6f7bf3)

![image](https://github.com/user-attachments/assets/e0054767-99f7-4728-8f98-512154c30e6d)

요청값에 faculty를 null로 요청 보냈을떄

기본 필터 로직으로 최신순으로 QuestionPost가 오지않습니다

# 반면에 

 개별 faculty를 지정했을때

잘보입니다

전체부분에서 일단 오류가 확인되었습니다

![image](https://github.com/user-attachments/assets/615f029a-c019-40e1-903e-331b1ed50a26)

![image](https://github.com/user-attachments/assets/f95a5aeb-c72f-435a-a969-aa5c22230e44)
![image](https://github.com/user-attachments/assets/96343d7f-6b9c-4fb1-a22a-ff14d8836553)

일단 백지훈님이 시간되시면 고쳐주세요 ~

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia  @Chuseok22

**Comment by Chuseok22** [comment]
#555 동일하게 수정했습니다~
@thswogh 버그 픽스 확인 후 이슈 닫아주세용~

**Comment by thswogh** [comment]
오류 해결 확인되었습니다!
