### ISSUE TITLE
🔥[긴급][api수정] 반환 파라미터 타입 변경에 따른 api 수정 요청

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#552]
🗒️ 설명
---
member의  `Faculty` 타입이 `<String>` 에서 `List< String >`으로 변경 되어 /api/document/filter API 입력 파라미터가 수정되어야 합니다
#529  참고
<br/>
### 현재  /api/document/filter API 
![image](https://github.com/user-attachments/assets/995e4bc7-7a05-45f4-949b-8a4fd3646db9)

🙋‍♂️ 담당자
---
누가 담당자인지 몰라서 새찬님으로 했는데 아니면 지훈님 태그 부탁드립니다
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
@Chuseok22 시간될때 먼저 봐주시면 감사하겠습니다!

**Comment by Chuseok22** [comment]
#555 확인하시구 이슈 닫아주세용~

**Comment by thswogh** [comment]
확인했습니다!

**Comment by Chuseok22** [comment]
@thswogh 이슈 다시 열었는데 잘못된 부분 있나요?

**Comment by Cassiiopeia** [comment]
닫아있~

**Comment by thswogh** [comment]
@Chuseok22 
다시 열어~ 
#555 스웨거에 반영해주시고 닫아주세요~
