### ISSUE TITLE
❗[버그][api로직문제] 질문메인 필터링 로직 문제

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#567]
🗒️ 설명
---
질문메인에서 "엽전 현상금 많은 순"으로 필터링 하면, 채택된 글은 안 나와야 할 것 같습니다
의도적으로 채택된 글도 필터링하신거면 밑에 저 태그하고 코멘트 남겨주세요~!
![image](https://github.com/user-attachments/assets/f0c10122-f8bc-47a7-89f0-b9eadaf99c7c)

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드: @thswogh

**Comment by Chuseok22** [comment]
확인했습니다~ 수정해놓을게요

**Comment by thswogh** [comment]
@Chuseok22 
그럼 아래와 같은 경우 (엽전현상금많은순 && 채택됨)에는 아무 글도 반환되지 않을까요?
![image](https://github.com/user-attachments/assets/48aa70e1-a99b-4ebb-b57f-0d96662116eb)

**Comment by Chuseok22** [comment]
엽전현상금 많은 순 필터링이 아직 채택 안된글 중 엽전 현상금 많은 글에 답변을 남기기위해 존재하는 기능이라 "엽전현상금" "채택됨"필터링은 공존하면 안 될 것 같습니다

**Comment by Chuseok22** [comment]
@thswogh 엽전 현상금 순으로 정렬시 자동으로 "미채택"필터링이 적용되게 구현했습니다.
![스크린샷 2024-12-06 오후 2 42 42](https://github.com/user-attachments/assets/869b19a5-6354-4640-b6b8-ada4b2892122)
![스크린샷 2024-12-06 오후 2 42 55](https://github.com/user-attachments/assets/1b24747b-b15f-40f4-b194-08bc0daa334b)
엽전현상금, 채택됨 필터링을 모두 적용했을 때 자동으로 채택됨 필터링은 무시됩니다.

**Comment by thswogh** [comment]
확인했습니다~!
