### ISSUE TITLE
🔥🔧  [긴급][기능요청][단과대] 단과대 리스트 API 요청

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#593]
🗒️ 설명
---
- 현재 프론트와 백이 단과대 리스트를 제가 아는것으로 fix된 정적인 값으로 가지고있는것으로압니다
- 내년에 단과대가 변하면 프론트에서는 변한 값을 알수없습니다

- 프론트에서 fix된 단과대를 사용하지않고, 현재 백에서 보내주는 단과대 정보를 통해서 label을 보여줘야합니다

- 일단 기본적으로 faculty findall해서 list로 보내주는 API가 필요합니다 완성되면
프론트 @thswogh 담당자로 이슈작성 부탁드립니다

![image](https://github.com/user-attachments/assets/3a20f85f-0e7b-44dd-b342-a0b5ba10cbbd)

해당부분입니다

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22

**Comment by Cassiiopeia** [comment]
@Chuseok22 

@Chuseok22 

![image](https://github.com/user-attachments/assets/fc1c9364-692a-4cd8-9336-7ee4bbbff4ed)


여기 dataiInitializer 여기에 run 메소드 

제일 하단에 

manageDataActiveStatus()

이런 메소드를 만들고 

거기안에서

// department isActive() 핸들링
// course isActive() 핸들링
// faculty isActive() 핸들링

이렇게 3개?? subject도 isActive()... 까지해야하나??
좀 봐야될같은데 

일단 지금 faculty부터하니까 

여기안에서 repository 단 돌면서

예를 들면 "수도여사대" 라는 name이 존재하면 setIsActive(false) 이런식으로 하고 save하는 로직 만들면 될것같습니다

안에 여러 값들이있는데 잘 확인해보고 

어떤식으로 구현할지.. 여러 방법이 생각이 나긴하는데

큰 들은

**Comment by Cassiiopeia** [comment]
해당 부분에서 가져와서 저희 DB에서 가져온값과 교집합 합니다

나무위키 짱짱맨
 
https://namu.wiki/w/%EC%84%B8%EC%A2%85%EB%8C%80%ED%95%99%EA%B5%90/%ED%95%99%EB%B6%80


<img width="424" alt="image" src="https://github.com/user-attachments/assets/3068ebe9-5e7c-4a17-9261-65de708c0851">


```
{
  "faculties": [
    {
      "facultyId": "a539d76a-75a6-415f-a175-c135e1bdbf24",
      "name": "경영경제대학",
      "isActive": true
    },
    {
      "facultyId": "65b56090-bc7d-4eab-9eff-bf4814300ae4",
      "name": "생명과학대학",
      "isActive": true
    },
    {
      "facultyId": "49a4a77c-7f41-433d-804a-405e214e12e9",
      "name": "인공지능융합대학",
      "isActive": true
    },
    {
      "facultyId": "be1c0529-e7d6-4248-b455-d43ab2edc660",
      "name": "예체능대학",
      "isActive": true
    },
    {
      "facultyId": "445d5b1d-c4b7-419a-aa12-47480e959aaa",
      "name": "자연과학대학",
      "isActive": true
    },
    {
      "facultyId": "2112fb3b-7f30-4ab8-93ad-f7056a2528c7",
      "name": "인문과학대학",
      "isActive": true
    },
    {
      "facultyId": "ac931126-3a5e-43c9-bf63-65951cbbbd9b",
      "name": "대양휴머니티칼리지",
      "isActive": true
    },
    {
      "facultyId": "05b0440d-68b2-45ef-840d-e92dd35f790c",
      "name": "사회과학대학",
      "isActive": true
    },
    {
      "facultyId": "056c2f6a-4a8e-4deb-b4a1-e19bd13a523f",
      "name": "호텔관광대학",
      "isActive": true
    },
    {
      "facultyId": "6202712d-6bc2-48ed-a2dc-62884a483945",
      "name": "공과대학",
      "isActive": true
    }
  ]
}
```

**Comment by Cassiiopeia** [comment]
@thswogh 
확인 부탁드립니다

**Comment by thswogh** [comment]
수정하겠습니다!

**Comment by Cassiiopeia** [comment]
@thswogh 담당자와 작업전으로 표시해놓겠습니다

**Comment by thswogh** [comment]
@Cassiiopeia  해당 api 요청 시 `Cannot serialize` 라는 에러가 나옵니다.
![image](https://github.com/user-attachments/assets/c677f6a9-20e1-42d8-b311-2d1e6004493d)
<br/>
![image](https://github.com/user-attachments/assets/8639b1e0-67c1-449d-8fa5-5912866e8496)

**Comment by Cassiiopeia** [comment]
@thswogh 수정했습니다 확인부탁드려요

**Comment by thswogh** [comment]
api 연동 완료하여 이슈 닫겠습니다
