### ISSUE TITLE
🚀 [기능개선][캐시] Redis를 사용한 캐시 기능 도입

### ISSUE THREAD

**Issue by Cassiiopeia** [Sejong-Balsamic/Malsami-BE#611]
🗒️ 설명
---
- 현재 스프링자체에서 지원하는 캐싱 기능을 사용중입니다

1. 레디스를 docker로 실행시켜야합니다 (시놀로지 gui 사용하면됩니다)
<img width="1407" alt="image" src="https://github.com/user-attachments/assets/89a5ed9f-a08d-4515-9a19-9f4a55de5597">
2. 레디스에 대한 설정값을 설정해줘야해요 컨테이너 실행시킬떄
: 아이디 비번은 팀원과 공유 부탁드립니다
3. 레디스를 어디에다가 사용할것인가
    - lock : post에 좋아요 올릴때 및 조회수 올릴때
    - 랜딩페이지에서 table에 id값을 넣고 이것을 findAll 한후 -> postRepo에서 findIn()해서 전체적으로 List<Post> 를 가져왔다면 이 table값이 아닌 인메모리 저장소 Redis안에 id값들을 저장함으로써 더 빠르게 랜딩페이지안에있는 값을 가져오게 할 수 있습니다 -> 아니면 그냥 id값이 아니라 List<Post> 자체를... 은 확인해봐야될것같습니다. Redis가 기본적으로 key value 저장소
    
 4. Faculty 정보를 가지고있는데 이부분도 잘 Redis에 저장이 되는지 체크해야합니다

⚙️ 작업 내용
---
- 기능 구현에 필요한 작업 항목을 작성합니다.
- 예: API 설계, 프론트엔드 화면 구성 등.

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22

**Comment by Chuseok22** [comment]
현재 좋아요/싫어요 증감 시 Lock기능까지 구현되어있습니다. 조회수 Lock기능도 추후 구현하겠습니다~

**Comment by Cassiiopeia** [comment]
<img width="1358" alt="image" src="https://github.com/user-attachments/assets/1fb17b96-fd3f-4cae-96e0-51d33efd134e" />

해당 PR conflict 해결후 main 반영 하였습니다

현재 계산로직이 잘 작동하고
redis에 잘 적재되는것을 확인하였습니다

<img width="228" alt="image" src="https://github.com/user-attachments/assets/faa6e294-6107-4c20-b563-1f52a295d4c4" />
<img width="326" alt="image" src="https://github.com/user-attachments/assets/6027eed3-f47b-4f64-8bd0-ae8340dd33ed" />
