### ISSUE TITLE
🔥 [긴급] 해외여행 issue...ㅎ

### ISSUE THREAD

**Issue by Chuseok22** [Sejong-Balsamic/Malsami-BE#620]
🗒️ 설명
---
현재까지 구현한 내용
1. 인기글 redis 로직
2. 좋아요/싫어요 증감 시 redisson lock 구현
3. logback-spring.xml 기본설정

추후 수정예정
1. 조회수 증가 시 redisson lock 로직 적용
2. logback-spring.xml 고도화

12/13 ~ 12/23 해외여행 이슈로 인해 작업이 어려운점 양해 부탁드립니다....ㅎㅎ
조심히 다녀오겠습니다 (_ _)

🙋‍♂️ 담당자
---
- 백엔드: @Chuseok22 
- 프론트엔드:
- 디자인:

**Comment by Cassiiopeia** [comment]
@Cassiiopeia 바톤터치했습니다 진행상황 업데이트하도록 하겠습니다 담당자로 표시해놓을께요. 잘 놀다오십쇼 ㅎㅎ
