### ISSUE TITLE
🔧 [기능요청][마이페이지] 게시판 입장 가능 여부 확인 기능

### ISSUE THREAD

**Issue by newjinlee** [Sejong-Balsamic/Malsami-BE#621]
🗒️ 설명
---
- 게시판 입장 가능 여부에 따라 프로필 이미지를 출력하고 있어 해당 기능이 필요합니다.
- api: member/my-page
- ![image](https://github.com/user-attachments/assets/1ab24399-36a4-4680-803e-10c198ace37d)
- ![image](https://github.com/user-attachments/assets/957055ff-505d-40de-b3f4-736c310fa2de)

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @newjinlee

**Comment by Cassiiopeia** [comment]
@newjinlee 이부분 api 있습니다
api/member/document/accessInfo

**Comment by newjinlee** [comment]
있는데 현재 천민 단계인 '이유진' 계정 기준
canAccessCheonmin = false; 나옵니다!

**Comment by Cassiiopeia** [comment]
@newjinlee 
해당 반환값에서

<img width="284" alt="image" src="https://github.com/user-attachments/assets/1a0bed5b-0d55-4c98-9107-c83b36ef0458" />


래퍼클래스가 아닌 기본 자료형으로 지정해놔서
null이 아닌우리가 값을 지정했는지 헷갈릴수있는 문제가 있었습니다

<img width="288" alt="image" src="https://github.com/user-attachments/assets/59b389de-0534-4075-8827-84693d2dbb0b" />


현재 래퍼클래스 로 변경하형 혼동을 줄였습니다
값을 지정하지않으면 null로 표시됩니다

해당 엔드포인트에 토큰과 함께 post요청을 보내면
/api/member/my-page

다음값이 추가됩니다

<img width="336" alt="스크린샷 2024-12-14 오후 6 07 03" src="https://github.com/user-attachments/assets/47d18075-5dab-401f-8851-ca13fcf44e16" />
