### ISSUE TITLE
⚙️ [기능추가] 전체 교과목명 서버에서 불러오기

### ISSUE THREAD

**Issue by thswogh** [Sejong-Balsamic/Malsami-BE#674]
🗒️ 설명
---
기존에는 프론트에서 `전체 교과목명`들이 하드코딩 되어있습니다.
`교과목명`들을 서버에서 불러오는 방식으로 수정해봅시다

**결론**: 전체 교과목명 주는 api 생성 부탁드립니다

작업완료하시면 하단의 프론트엔드 이슈에 언급 부탁드립니다
https://github.com/Sejong-Balsamic/Malsami-FE/issues/388

🙋‍♂️ 담당자
---
- 백엔드: @Cassiiopeia 
- 프론트엔드: @thswogh

**Comment by Cassiiopeia** [comment]
@thswogh  구현했습니다 확인 부탁드립니다

![image](https://github.com/user-attachments/assets/1cbeeb1e-5831-4504-9b3e-42629377a5ef)

![image](https://github.com/user-attachments/assets/b4347507-e81f-4dd6-8592-c50f958075d0)

**Comment by Cassiiopeia** [comment]
담당자 변경합니다 @thswogh

**Comment by thswogh** [comment]
확인했습니다. 프론트에 반영하겠습니다
